server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml+rss application/javascript application/json font/ttf font/otf font/woff font/woff2 application/font-woff application/font-woff2;

    location = /health {
        return 200 'ok';
        add_header Content-Type text/plain;
        access_log off;
    }

    location ^~ /remotes/core-business/ {
        rewrite ^/remotes/(.*)$ /$1 break;
        try_files $uri $uri/ =404;
    }

    location ^~ /core-business/ {
        try_files $uri $uri/ /core-business/index.html;
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
}
